### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageFlag = "ğŸ‡¬ğŸ‡§" # custom
  #languageCode = "en"
  #languageCodeCountry = "DO_NOT_USE"  # custom
  #timeZone = "Etc/UTC"
  #tzOffset = "0h" # custom
  #tzAbbr = "UTC"  # custom
  #weight = 110

[en-ph]
  languageName = "English (PH)"
  languageFlag = "ğŸ‡µğŸ‡­" # custom
  languageCode = "en-PH"
  languageCodeCountry = "ph"  # custom
  timeZone = "Asia/Manila"
  tzOffset = "8h" # custom
  tzAbbr = "PHT"  # custom
  weight = 111
  [[en-ph.menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [en-ph.menu.main.params]
      newTab = false

#[fil]
  #languageName = "Filipino"
  #languageFlag = "ğŸ‡µğŸ‡­" # custom
  #languageCode = "fil"
  #languageCodeCountry = "ph"  # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h" # custom
  #tzAbbr = "PHT"  # custom
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageFlag = "ğŸ‡µğŸ‡­" # custom
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"  # custom
  #timeZone = "Asia/Manila"
  #tzOffset = "8h" # custom
  #tzAbbr = "PHT"  # custom
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³" # custom
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"  # custom
  #timeZone = "Asia/Shanghai"
  #tzOffset = "8h" # custom
  #tzAbbr = "CST"  # custom
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³" # custom
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"  # custom
  #timeZone = "Asia/Shanghai"
  #tzOffset = "8h" # custom
  #tzAbbr = "CST"  # custom
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageFlag = "ğŸ‡¯ğŸ‡µ" # custom
  languageCode = "ja"
  languageCodeCountry = "jp"  # custom
  timeZone = "Asia/Tokyo"
  tzOffset = "9h" # custom
  tzAbbr = "JST"  # custom
  weight = 140
  title = "ãƒã‚¤ãƒ†ã‚¯ ãƒã‚®"
  [[ja.menu.main]]
    name              = "ãƒ›ãƒ¼ãƒ "
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ja.menu.main.params]
      newTab = false
  [ja.params]
    description = "ç§‘å­¦æŠ€è¡“ã®éŠã³å ´"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ko]
  languageName = "í•œêµ­ì–´"
  languageFlag = "ğŸ‡°ğŸ‡·" # custom
  languageCode = "ko"
  languageCodeCountry = "kr"  # custom
  timeZone = "Asia/Seoul"
  tzOffset = "9h" # custom
  tzAbbr = "KST"  # custom; í•œêµ­ì‹œê°„
  weight = 150
  title = "í…Œí¬ ë§ˆêµ¬ìŠ¤"
  [[ko.menu.main]]
    name              = "ì§‘"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ko.menu.main.params]
      newTab = false
  [ko.params]
    description = "ê³¼í•™ ê¸°ìˆ  ë†€ì´í„°"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
