# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

[en-ph]
  [[en-ph.menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [en-ph.menu.main.params]
      newTab = false

[ja]
  title = "ãƒã‚¤ãƒ†ã‚¯ ãƒã‚® ğŸš€"
  [[ja.menu.main]]
    name              = "ãƒ›ãƒ¼ãƒ "
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ja.menu.main.params]
      newTab = false
  [ja.params]
    description = "ç§‘å­¦æŠ€è¡“ã®éŠã³å ´"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ko]
  title = "í…Œí¬ ë§ˆêµ¬ìŠ¤ ğŸš€"
  [[ko.menu.main]]
    name              = "ì§‘"
    identifier        = "home"
    url               = "/"
    pre               = "home"
    weight            = 1
    [ko.menu.main.params]
      newTab = false
  [ko.params]
    description = "ê³¼í•™ ê¸°ìˆ  ë†€ì´í„°"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
